import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Shared/navbar/Navbar";
import Footer from "@/components/Shared/footer/Footer";
import { Toaster } from "react-hot-toast";
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >
      <body
        className={`${inter.className} min-h-full flex flex-col`}
        cz-shortcut-listen="true"
      >
        <Navbar></Navbar>
        <main>{children}</main>
        <Footer></Footer>
        <Toaster
          position="top-center"
          reverseOrder={false}
          gutter={8}
          toastOptions={{
            duration: 4000,
            style: {
              background: "#FFFFFF",
              color: "#0F172A",
              fontFamily: "inherit",
              fontSize: "14px",
              fontWeight: "500",
              letterSpacing: "0.01em",
              padding: "12px 16px",
              borderRadius: "8px",
              border: "1px solid #E2E8F0",
              boxShadow:
                "0 4px 6px -1px rgb(0 0 0 / 0.05), 0 2px 4px -2px rgb(0 0 0 / 0.05)",
              maxWidth: "420px",
            },
            success: {
              iconTheme: {
                primary: "#0EA5E9",
                secondary: "#FFFFFF",
              },
            },
            error: {
              iconTheme: {
                primary: "#EF4444",
                secondary: "#FFFFFF",
              },
            },
          }}
        />
      </body>
    </html>
  );
}
